### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by zimingyy** [sunericd/dynamic-visualization-of-high-dimensional-data#1]
Can you share your dataset, such as svz_buckley_data_full_processed_v2k.csv, svz_buckley_meta_full.csv, svz_data.csv, svz_buckley_data_full_processed_v2k.csv and so on
thanks very much!

**Comment by sunericd** [comment]
Thanks for the inquiry. The intermediate data files can be quite large and not the easiest to share. You can download the raw data from the links in the Data Availability section of our manuscript (https://www.nature.com/articles/s43588-022-00380-4#data-availability). From there, you can extract the counts matrix (e.g. for svz data, this would give you svz_buckley_data_full_processed.csv) and the associated metadata (e.g. this would give you svz_buckley_meta_full.csv). Then, you can downsample them to 1k or 2k cells to get the smaller datasets (we generally find consistent findings across different downsampled datasets). Hopefully this makes sense and let me know if you run into any issues!
